//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeRegistration.Models
{
    using System;
    using System.Collections.Generic;
    using TimeRegistration.Enums;
    
    public partial class Entry
    {
        public int Id { get; set; }
        public int Hours { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public Nullable<int> AbsenceReason { get; set; }
        public string Message { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> TaskId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Task Task { get; set; }
    }
}
